const dutchTeams = [
	{
		infogol: "Ajax",
		today: "Ajax",
		oddsportal: "Ajax",
	},
	{
		infogol: "PSV",
		today: "PSV",
		oddsportal: "PSV",
	},
	{
		infogol: "Feyenoord",
		today: "Feyenoord",
		oddsportal: "Feyenoord",
	},
	{
		infogol: "Vitesse",
		today: "Vitesse",
		oddsportal: "Vitesse",
	},
	{
		infogol: "FC Groningen",
		today: "Groningen",
		oddsportal: "Groningen",
	},
	{
		infogol: "FC Twente",
		today: "Twente",
		oddsportal: "Twente",
	},
	{
		infogol: "AZ",
		today: "AZ Alkmaar",
		oddsportal: "AZ Alkmaar",
	},
	{
		infogol: "SC Heerenveen",
		today: "Heerenveen",
		oddsportal: "Heerenveen",
	},
	{
		infogol: "Sparta Rotterdam",
		today: "Sparta Rotterdam",
		oddsportal: "Sparta Rotterdam",
	},
	{
		infogol: "FC Utrecht",
		today: "Utrecht",
		oddsportal: "Utrecht",
	},
	{
		infogol: "PEC Zwolle",
		today: "PEC Zwolle",
		oddsportal: "Zwolle",
	},
	{
		infogol: "RKC Waalwijk",
		today: "RKC Waalwijk",
		oddsportal: "Waalwijk",
	},
	{
		infogol: "Heracles Almelo",
		today: "Heracles",
		oddsportal: "Heracles",
	},
	{
		infogol: "Fortuna Sittard",
		today: "Fortuna Sittard",
		oddsportal: "Sittard",
	},
	{
		infogol: "VVV-Venlo",
		today: "VVV-Venlo",
		oddsportal: "Venlo",
	},
	{
		infogol: "Willem II",
		today: "Willem II",
		oddsportal: "Willem II",
	},
	{
		infogol: "ADO Den Haag",
		today: "ADO Den Haag",
		oddsportal: "Den Haag",
	},
	{
		infogol: "FC Emmen",
		today: "Emmen",
		oddsportal: "FC Emmen",
	},
	{
		infogol: "Liverpool",
		today: "Liverpool",
		oddsportal: "Liverpool",
	},
	{
		infogol: "Everton",
		today: "Everton",
		oddsportal: "Everton",
	},
	{
		infogol: "Tottenham Hotspur",
		today: "Tottenham",
		oddsportal: "Tottenham",
	},
	{
		infogol: "Leicester City",
		today: "Leicester",
		oddsportal: "Leicester",
	},
	{
		infogol: "Southampton",
		today: "Southampton",
		oddsportal: "Southampton",
	},
	{
		infogol: "Manchester City",
		today: "Man City",
		oddsportal: "Manchester City",
	},
	{
		infogol: "Manchester United",
		today: "Man Utd",
		oddsportal: "Manchester Utd",
	},
	{
		infogol: "Chelsea",
		today: "Chelsea",
		oddsportal: "Chelsea",
	},
	{
		infogol: "West Ham United",
		today: "West Ham",
		oddsportal: "West Ham",
	},
	{
		infogol: "Wolverhampton Wanderers",
		today: "Wolves",
		oddsportal: "Wolves",
	},
	{
		infogol: "Aston Villa",
		today: "Aston Villa",
		oddsportal: "Aston Villa",
	},
	{
		infogol: "Newcastle United",
		today: "Newcastle",
		oddsportal: "Newcastle",
	},
	{
		infogol: "Crystal Palace",
		today: "Crystal Palace",
		oddsportal: "Crystal Palace",
	},
	{
		infogol: "Leeds United",
		today: "Leeds",
		oddsportal: "Leeds",
	},
	{
		infogol: "Arsenal",
		today: "Arsenal",
		oddsportal: "Arsenal",
	},
	{
		infogol: "Brighton and Hove Albion",
		today: "Brighton",
		oddsportal: "Brighton",
	},
	{
		infogol: "Fulham",
		today: "Fulham",
		oddsportal: "Fulham",
	},
	{
		infogol: "Burnley",
		today: "Burnley",
		oddsportal: "Burnley",
	},
	{
		infogol: "West Bromwich Albion",
		today: "West Brom",
		oddsportal: "West Brom",
	},
	{
		infogol: "Sheffield United",
		today: "Sheff Utd",
		oddsportal: "Sheffield Utd",
	},
	{
		infogol: "AC Milan",
		today: "AC Milan",
		oddsportal: "AC Milan",
	},
	{
		infogol: "Inter Milan",
		today: "Inter Milan",
		oddsportal: "Inter",
	},
	{
		infogol: "Napoli",
		today: "Napoli",
		oddsportal: "Napoli",
	},
	{
		infogol: "Juventus",
		today: "Juventus",
		oddsportal: "Juventus",
	},
	{
		infogol: "Sassuolo",
		today: "Sassuolo",
		oddsportal: "Sassuolo",
	},
	{
		infogol: "Roma",
		today: "Roma",
		oddsportal: "AS Roma",
	},
	{
		infogol: "Verona",
		today: "Verona",
		oddsportal: "Verona",
	},
	{
		infogol: "Lazio",
		today: "Lazio",
		oddsportal: "Lazio",
	},
	{
		infogol: "Atalanta",
		today: "Atalanta",
		oddsportal: "Atalanta",
	},
	{
		infogol: "Udinese",
		today: "Udinese",
		oddsportal: "Udinese",
	},
	{
		infogol: "Cagliari",
		today: "Cagliari",
		oddsportal: "Cagliari",
	},
	{
		infogol: "Bologna",
		today: "Bologna",
		oddsportal: "Bologna",
	},
	{
		infogol: "Benevento",
		today: "Benevento",
		oddsportal: "Benevento",
	},
	{
		infogol: "Sampdoria",
		today: "Sampdoria",
		oddsportal: "Sampdoria",
	},
	{
		infogol: "Parma",
		today: "Parma",
		oddsportal: "Parma",
	},
	{
		infogol: "Spezia",
		today: "Spezia",
		oddsportal: "Spezia",
	},
	{
		infogol: "Fiorentina",
		today: "Fiorentina",
		oddsportal: "Fiorentina",
	},
	{
		infogol: "Torino",
		today: "Torino",
		oddsportal: "Torino",
	},
	{
		infogol: "Genoa",
		today: "Genoa",
		oddsportal: "Genoa",
	},
	{
		infogol: "Crotone",
		today: "Crotone",
		oddsportal: "Crotone",
	},
	{
		infogol: "Lyon",
		today: "Lyon",
		oddsportal: "Lyon",
	},
	{
		infogol: "Lille",
		today: "Lille",
		oddsportal: "Lille",
	},
	{
		infogol: "Paris Saint-Germain",
		today: "PSG",
		oddsportal: "Paris SG",
	},
	{
		infogol: "Marseille",
		today: "Marseille",
		oddsportal: "Marseille",
	},
	{
		infogol: "Montpellier",
		today: "Montpellier",
		oddsportal: "Montpellier",
	},
	{
		infogol: "Rennes",
		today: "Rennes",
		oddsportal: "Rennes",
	},
	{
		infogol: "Lens",
		today: "Lens",
		oddsportal: "Lens",
	},
	{
		infogol: "Metz",
		today: "Metz",
		oddsportal: "Metz",
	},
	{
		infogol: "Monaco",
		today: "Monaco",
		oddsportal: "Monaco",
	},
	{
		infogol: "Angers",
		today: "Angers",
		oddsportal: "Angers",
	},
	{
		infogol: "Brest",
		today: "Brest",
		oddsportal: "Brest",
	},
	{
		infogol: "Nice",
		today: "Nice",
		oddsportal: "Nice",
	},
	{
		infogol: "Bordeaux",
		today: "Bordeaux",
		oddsportal: "Bordeaux",
	},
	{
		infogol: "St Etienne",
		today: "St Etienne",
		oddsportal: "St Etienne",
	},
	{
		infogol: "Strasbourg",
		today: "Strasbourg",
		oddsportal: "Strasbourg",
	},
	{
		infogol: "Reims",
		today: "Reims",
		oddsportal: "Reims",
	},
	{
		infogol: "Nantes",
		today: "Nantes",
		oddsportal: "Nantes",
	},
	{
		infogol: "Lorient",
		today: "Lorient",
		oddsportal: "Lorient",
	},
	{
		infogol: "Nîmes",
		today: "Nimes",
		oddsportal: "Nimes",
	},
	{
		infogol: "Dijon",
		today: "Dijon",
		oddsportal: "Dijon",
	},
	{
		infogol: "Bayer 04 Leverkusen",
		today: "Bayer Leverkusen",
		oddsportal: "Bayer Leverkusen",
	},
	{
		infogol: "FC Bayern München",
		today: "Bayern Munich",
		oddsportal: "Bayern Munich",
	},
	{
		infogol: "RB Leipzig",
		today: "RB Leipzig",
		oddsportal: "RB Leipzig",
	},
	{
		infogol: "Borussia Dortmund",
		today: "Dortmund",
		oddsportal: "Dortmund",
	},
	{
		infogol: "VfL Wolfsburg",
		today: "Wolfsburg",
		oddsportal: "Wolfsburg",
	},
	{
		infogol: "1. FC Union Berlin",
		today: "Union Berlin",
		oddsportal: "Union Berlin",
	},
	{
		infogol: "VfB Stuttgart",
		today: "Stuttgart",
		oddsportal: "Stuttgart",
	},
	{
		infogol: "Borussia Mönchengladbach",
		today: "Mönchengladbach",
		oddsportal: "B. Monchengladbach",
	},
	{
		infogol: "Eintracht Frankfurt",
		today: "Eintracht Frankfurt",
		oddsportal: "Eintracht Frankfurt",
	},
	{
		infogol: "Hertha BSC",
		today: "Hertha Berlin",
		oddsportal: "Hertha Berlin",
	},
	{
		infogol: "FC Augsburg",
		today: "Augsburg",
		oddsportal: "Augsburg",
	},
	{
		infogol: "TSG 1899 Hoffenheim",
		today: "Hoffenheim",
		oddsportal: "Hoffenheim",
	},
	{
		infogol: "SV Werder Bremen",
		today: "Werder Bremen",
		oddsportal: "Werder Bremen",
	},
	{
		infogol: "SC Freiburg",
		today: "Freiburg",
		oddsportal: "Freiburg",
	},
	{
		infogol: "1. FC Köln",
		today: "FC Köln",
		oddsportal: "FC Koln",
	},
	{
		infogol: "DSC Arminia Bielefeld",
		today: "Arminia Bielefeld",
		oddsportal: "Arminia Bielefeld",
	},
	{
		infogol: "1. FSV Mainz 05",
		today: "Mainz",
		oddsportal: "Mainz",
	},
	{
		infogol: "FC Schalke 04",
		today: "Schalke",
		oddsportal: "Schalke",
	},
	{
		infogol: "Norwich City",
		today: "Norwich",
		oddsportal: "Norwich",
	},
	{
		infogol: "Bournemouth",
		today: "Bournemouth",
		oddsportal: "Bournemouth",
	},
	{
		infogol: "Swansea City",
		today: "Swansea",
		oddsportal: "Swansea",
	},
	{
		infogol: "Brentford",
		today: "Brentford",
		oddsportal: "Brentford",
	},
	{
		infogol: "Watford",
		today: "Watford",
		oddsportal: "Watford",
	},
	{
		infogol: "Middlesbrough",
		today: "Middlesbrough",
		oddsportal: "Middlesbrough",
	},
	{
		infogol: "Stoke City",
		today: "Stoke",
		oddsportal: "Stoke",
	},
	{
		infogol: "Reading",
		today: "Reading",
		oddsportal: "Reading",
	},
	{
		infogol: "Bristol City",
		today: "Bristol City",
		oddsportal: "Bristol City",
	},
	{
		infogol: "Cardiff City",
		today: "Cardiff",
		oddsportal: "Cardiff",
	},
	{
		infogol: "Blackburn Rovers",
		today: "Blackburn",
		oddsportal: "Blackburn",
	},
	{
		infogol: "Huddersfield Town",
		today: "Huddersfield",
		oddsportal: "Huddersfield",
	},
	{
		infogol: "Barnsley",
		today: "Barnsley",
		oddsportal: "Barnsley",
	},
	{
		infogol: "Luton Town",
		today: "Luton",
		oddsportal: "Luton",
	},
	{
		infogol: "Preston North End",
		today: "Preston",
		oddsportal: "Preston",
	},
	{
		infogol: "Millwall",
		today: "Millwall",
		oddsportal: "Millwall",
	},
	{
		infogol: "Birmingham City",
		today: "Birmingham",
		oddsportal: "Birmingham",
	},
	{
		infogol: "Coventry City",
		today: "Coventry",
		oddsportal: "Coventry",
	},
	{
		infogol: "Queens Park Rangers",
		today: "QPR",
		oddsportal: "QPR",
	},
	{
		infogol: "Nottingham Forest",
		today: "Forest",
		oddsportal: "Nottingham",
	},
	{
		infogol: "Rotherham United",
		today: "Rotherham",
		oddsportal: "Rotherham",
	},
	{
		infogol: "Derby County",
		today: "Derby",
		oddsportal: "Derby",
	},
	{
		infogol: "Sheffield Wednesday",
		today: "Sheff Wed",
		oddsportal: "Sheffield Wed",
	},
	{
		infogol: "Wycombe Wanderers",
		today: "Wycombe",
		oddsportal: "Wycombe",
	},
	{
		infogol: "Atlético de Madrid",
		today: "Atlético Madrid",
		oddsportal: "Atl. Madrid",
	},
	{
		infogol: "Real Madrid",
		today: "Real Madrid",
		oddsportal: "Real Madrid",
	},
	{
		infogol: "Real Sociedad",
		today: "Real Sociedad",
		oddsportal: "Real Sociedad",
	},
	{
		infogol: "Villarreal",
		today: "Villarreal",
		oddsportal: "Villarreal",
	},
	{
		infogol: "Barcelona",
		today: "Barcelona",
		oddsportal: "Barcelona",
	},
	{
		infogol: "Sevilla",
		today: "Sevilla",
		oddsportal: "Sevilla",
	},
	{
		infogol: "Granada CF",
		today: "Granada",
		oddsportal: "Granada CF",
	},
	{
		infogol: "Celta de Vigo",
		today: "Celta Vigo",
		oddsportal: "Celta Vigo",
	},
	{
		infogol: "Real Betis",
		today: "Real Betis",
		oddsportal: "Betis",
	},
	{
		infogol: "Athletic Club",
		today: "Athletic Bilbao",
		oddsportal: "Ath Bilbao",
	},
	{
		infogol: "Cádiz",
		today: "Cadiz",
		oddsportal: "Cadiz CF",
	},
	{
		infogol: "Getafe",
		today: "Getafe",
		oddsportal: "Getafe",
	},
	{
		infogol: "Alavés",
		today: "Alaves",
		oddsportal: "Alaves",
	},
	{
		infogol: "Valencia CF",
		today: "Valencia",
		oddsportal: "Valencia",
	},
	{
		infogol: "Levante",
		today: "Levante",
		oddsportal: "Levante",
	},
	{
		infogol: "Elche",
		today: "Elche",
		oddsportal: "Elche",
	},
	{
		infogol: "Eibar",
		today: "Eibar",
		oddsportal: "Eibar",
	},
	{
		infogol: "Real Valladolid",
		today: "Real Valladolid",
		oddsportal: "Valladolid",
	},
	{
		infogol: "Osasuna",
		today: "Osasuna",
		oddsportal: "Osasuna",
	},
	{
		infogol: "Huesca",
		today: "Huesca",
		oddsportal: "Huesca",
	},
	{
		infogol: "Sporting Lisbon",
		today: "Sporting CP",
		oddsportal: "Sporting",
	},
	{
		infogol: "Benfica",
		today: "Benfica",
		oddsportal: "Benfica",
	},
	{
		infogol: "FC Porto",
		today: "Porto",
		oddsportal: "FC Porto",
	},
	{
		infogol: "Sporting Braga",
		today: "SC Braga",
		oddsportal: "Braga",
	},
	{
		infogol: "Vitória Guimarães",
		today: "Guimarães",
		oddsportal: "Vitoria Guimaraes",
	},
	{
		infogol: "Paços de Ferreira",
		today: "Ferreira",
		oddsportal: "Ferreira",
	},
	{
		infogol: "Santa Clara",
		today: "Santa Clara",
		oddsportal: "Santa Clara",
	},
	{
		infogol: "FC Famalicão",
		today: "Famalicão",
		oddsportal: "Famalicao",
	},
	{
		infogol: "Rio Ave",
		today: "Rio Ave",
		oddsportal: "Rio Ave",
	},
	{
		infogol: "Belenenses",
		today: "Belenenses",
		oddsportal: "Belenenses",
	},
	{
		infogol: "Moreirense",
		today: "Moreirense",
		oddsportal: "Moreirense",
	},
	{
		infogol: "Marítimo",
		today: "Marítimo",
		oddsportal: "Maritimo",
	},
	{
		infogol: "CD Nacional",
		today: "Nacional",
		oddsportal: "Nacional",
	},
	{
		infogol: "Gil Vicente",
		today: "Gil Vicente",
		oddsportal: "Gil Vicente",
	},
	{
		infogol: "Tondela",
		today: "Tondela",
		oddsportal: "Tondela",
	},
	{
		infogol: "Boavista",
		today: "Boavista",
		oddsportal: "Boavista",
	},
	{
		infogol: "SC Farense",
		today: "Farense",
		oddsportal: "SC Farense",
	},
	{
		infogol: "Portimonense",
		today: "Portimonense",
		oddsportal: "Portimonense",
	},
	{
		infogol: "Adelaide United",
		today: "Adelaide United",
		oddsportal: "Adelaide United",
	},
	{
		infogol: "Brisbane Roar FC",
		today: "Brisbane Roar",
		oddsportal: "Brisbane Roar",
	},
	{
		infogol: "Central Coast Mariners",
		today: "Central Coast",
		oddsportal: "Central Coast Mariners",
	},
	{
		infogol: "Macarthur FC",
		today: "Macarthur FC",
		oddsportal: "Macarthur FC",
	},
	{
		infogol: "Melbourne City FC",
		today: "Melbourne City",
		oddsportal: "Melbourne City",
	},
	{
		infogol: "Melbourne Victory",
		today: "Melbourne Victory",
		oddsportal: "Melbourne Victory",
	},
	{
		infogol: "Newcastle Jets",
		today: "Newcastle Jets",
		oddsportal: "Newcastle Jets",
	},
	{ infogol: "Perth Glory", today: "Perth Glory", oddsportal: "Perth Glory" },
	{ infogol: "Sydney FC", today: "Sydney FC", oddsportal: "Sydney FC" },
	{
		infogol: "Wellington Phoenix",
		today: "Wellington Phoenix",
		oddsportal: "Wellington Phoenix",
	},
	{
		infogol: "Western Sydney Wanderers FC",
		today: "Western Sydney Wanderers",
		oddsportal: "WS Wanderers",
	},
	{
		infogol: "Western United FC",
		today: "Western United",
		oddsportal: "Western United",
	},
];
const urlsIdDutch = [
	62,
	98,
	116,
	479,
	145,
	331,
	141,
	404,
	1656,
	450,
	1644,
	1650,
	288,
	1639,
	1661,
	1663,
	1617,
	1626,
	77,
	112,
	139,
	163,
	164,
	80,
	97,
	69,
	169,
	25,
	32,
	35,
	162,
	15,
	64,
	8,
	12,
	27,
	168,
	345,
	325,
	123,
	128,
	76,
	267,
	85,
	772,
	150,
	477,
	337,
	767,
	766,
	765,
	770,
	401,
	820,
	117,
	138,
	769,
	768,
	95,
	126,
	84,
	153,
	1171,
	1109,
	385,
	1234,
	81,
	1225,
	1233,
	321,
	143,
	135,
	1231,
	1230,
	1228,
	1452,
	1229,
	1227,
	66,
	72,
	475,
	68,
	99,
	956,
	338,
	90,
	405,
	261,
	144,
	474,
	412,
	461,
	476,
	960,
	324,
	74,
	18,
	6,
	167,
	7,
	23,
	16,
	165,
	20,
	26,
	9,
	3,
	13,
	33,
	341,
	30,
	17,
	2,
	340,
	31,
	19,
	21,
	11,
	22,
	887,
	38,
	51,
	52,
	55,
	39,
	53,
	47,
	40,
	57,
	37,
	469,
	46,
	59,
	54,
	48,
	44,
	43,
	457,
	61,
	1016,
	88,
	67,
	73,
	160,
	480,
	1655,
	1662,
	1641,
	132,
	142,
	1653,
	336,
	413,
	1646,
	1667,
	1635,
	1732,
	1659,
	1525,
	1526,
	1528,
	1806,
	1530,
	1532,
	1534,
	1535,
	1537,
	1539,
	1541,
	1543,
];
module.exports = {
	dutchTeams,
	urlsIdDutch,
};
