const dutchTeams = [
	{ infogol: "Ajax", today: "Ajax", oddsportal: "Ajax" },
	{ infogol: "PSV", today: "PSV", oddsportal: "PSV" },
	{ infogol: "Feyenoord", today: "Feyenoord", oddsportal: "Feyenoord" },
	{ infogol: "Vitesse", today: "Vitesse", oddsportal: "Vitesse" },
	{ infogol: "FC Groningen", today: "Groningen", oddsportal: "Groningen" },
	{ infogol: "FC Twente", today: "Twente", oddsportal: "Twente" },
	{ infogol: "AZ", today: "AZ Alkmaar", oddsportal: "AZ Alkmaar" },
	{ infogol: "SC Heerenveen", today: "Heerenveen", oddsportal: "Heerenveen" },
	{
		infogol: "Sparta Rotterdam",
		today: "Sparta Rotterdam",
		oddsportal: "Sparta Rotterdam",
	},
	{ infogol: "FC Utrecht", today: "Utrecht", oddsportal: "Utrecht" },
	{ infogol: "PEC Zwolle", today: "PEC Zwolle", oddsportal: "Zwolle" },
	{ infogol: "RKC Waalwijk", today: "RKC Waalwijk", oddsportal: "Waalwijk" },
	{ infogol: "Heracles Almelo", today: "Heracles", oddsportal: "Heracles" },
	{
		infogol: "Fortuna Sittard",
		today: "Fortuna Sittard",
		oddsportal: "Sittard",
	},
	{ infogol: "VVV-Venlo", today: "VVV-Venlo", oddsportal: "Venlo" },
	{ infogol: "Willem II", today: "Willem II", oddsportal: "Willem II" },
	{ infogol: "ADO Den Haag", today: "ADO Den Haag", oddsportal: "Den Haag" },
	{ infogol: "FC Emmen", today: "Emmen", oddsportal: "FC Emmen" },
	{ infogol: "Liverpool", today: "Liverpool", oddsportal: "Liverpool" },
	{ infogol: "Everton", today: "Everton", oddsportal: "Everton" },
	{
		infogol: "Tottenham Hotspur",
		today: "Tottenham",
		oddsportal: "Tottenham",
	},
	{ infogol: "Leicester City", today: "Leicester", oddsportal: "Leicester" },
	{ infogol: "Southampton", today: "Southampton", oddsportal: "Southampton" },
	{
		infogol: "Manchester City",
		today: "Man City",
		oddsportal: "Manchester City",
	},
	{
		infogol: "Manchester United",
		today: "Man Utd",
		oddsportal: "Manchester Utd",
	},
	{ infogol: "Chelsea", today: "Chelsea", oddsportal: "Chelsea" },
	{ infogol: "West Ham United", today: "West Ham", oddsportal: "West Ham" },
	{
		infogol: "Wolverhampton Wanderers",
		today: "Wolves",
		oddsportal: "Wolves",
	},
	{ infogol: "Aston Villa", today: "Aston Villa", oddsportal: "Aston Villa" },
	{ infogol: "Newcastle United", today: "Newcastle", oddsportal: "Newcastle" },
	{
		infogol: "Crystal Palace",
		today: "Crystal Palace",
		oddsportal: "Crystal Palace",
	},
	{ infogol: "Leeds United", today: "Leeds", oddsportal: "Leeds" },
	{ infogol: "Arsenal", today: "Arsenal", oddsportal: "Arsenal" },
	{
		infogol: "Brighton and Hove Albion",
		today: "Brighton",
		oddsportal: "Brighton",
	},
	{ infogol: "Fulham", today: "Fulham", oddsportal: "Fulham" },
	{ infogol: "Burnley", today: "Burnley", oddsportal: "Burnley" },
	{
		infogol: "West Bromwich Albion",
		today: "West Brom",
		oddsportal: "West Brom",
	},
	{
		infogol: "Sheffield United",
		today: "Sheff Utd",
		oddsportal: "Sheffield Utd",
	},
	{ infogol: "AC Milan", today: "AC Milan", oddsportal: "AC Milan" },
	{ infogol: "Inter Milan", today: "Inter Milan", oddsportal: "Inter" },
	{ infogol: "Napoli", today: "Napoli", oddsportal: "Napoli" },
	{ infogol: "Juventus", today: "Juventus", oddsportal: "Juventus" },
	{ infogol: "Sassuolo", today: "Sassuolo", oddsportal: "Sassuolo" },
	{ infogol: "Roma", today: "Roma", oddsportal: "AS Roma" },
	{ infogol: "Verona", today: "Verona", oddsportal: "Verona" },
	{ infogol: "Lazio", today: "Lazio", oddsportal: "Lazio" },
	{ infogol: "Atalanta", today: "Atalanta", oddsportal: "Atalanta" },
	{ infogol: "Udinese", today: "Udinese", oddsportal: "Udinese" },
	{ infogol: "Cagliari", today: "Cagliari", oddsportal: "Cagliari" },
	{ infogol: "Bologna", today: "Bologna", oddsportal: "Bologna" },
	{ infogol: "Benevento", today: "Benevento", oddsportal: "Benevento" },
	{ infogol: "Sampdoria", today: "Sampdoria", oddsportal: "Sampdoria" },
	{ infogol: "Parma", today: "Parma", oddsportal: "Parma" },
	{ infogol: "Spezia", today: "Spezia", oddsportal: "Spezia" },
	{ infogol: "Fiorentina", today: "Fiorentina", oddsportal: "Fiorentina" },
	{ infogol: "Torino", today: "Torino", oddsportal: "Torino" },
	{ infogol: "Genoa", today: "Genoa", oddsportal: "Genoa" },
	{ infogol: "Crotone", today: "Crotone", oddsportal: "Crotone" },
	{ infogol: "Lyon", today: "Lyon", oddsportal: "Lyon" },
	{ infogol: "Lille", today: "Lille", oddsportal: "Lille" },
	{ infogol: "Paris Saint-Germain", today: "PSG", oddsportal: "Paris SG" },
	{ infogol: "Marseille", today: "Marseille", oddsportal: "Marseille" },
	{ infogol: "Montpellier", today: "Montpellier", oddsportal: "Montpellier" },
	{ infogol: "Rennes", today: "Rennes", oddsportal: "Rennes" },
	{ infogol: "Lens", today: "Lens", oddsportal: "Lens" },
	{ infogol: "Metz", today: "Metz", oddsportal: "Metz" },
	{ infogol: "Monaco", today: "Monaco", oddsportal: "Monaco" },
	{ infogol: "Angers", today: "Angers", oddsportal: "Angers" },
	{ infogol: "Brest", today: "Brest", oddsportal: "Brest" },
	{ infogol: "Nice", today: "Nice", oddsportal: "Nice" },
	{ infogol: "Bordeaux", today: "Bordeaux", oddsportal: "Bordeaux" },
	{ infogol: "St Etienne", today: "St Etienne", oddsportal: "St Etienne" },
	{ infogol: "Strasbourg", today: "Strasbourg", oddsportal: "Strasbourg" },
	{ infogol: "Reims", today: "Reims", oddsportal: "Reims" },
	{ infogol: "Nantes", today: "Nantes", oddsportal: "Nantes" },
	{ infogol: "Lorient", today: "Lorient", oddsportal: "Lorient" },
	{ infogol: "Nîmes", today: "Nimes", oddsportal: "Nimes" },
	{ infogol: "Dijon", today: "Dijon", oddsportal: "Dijon" },
];
const urlsIdDutch = [
	62,
	98,
	116,
	479,
	145,
	331,
	141,
	404,
	1656,
	450,
	1644,
	1650,
	288,
	1639,
	1661,
	1663,
	1617,
	1626,
	77,
	112,
	139,
	163,
	164,
	80,
	97,
	69,
	169,
	25,
	32,
	35,
	162,
	15,
	64,
	8,
	12,
	27,
	168,
	345,
	325,
	123,
	128,
	76,
	267,
	85,
	772,
	150,
	477,
	337,
	767,
	766,
	765,
	770,
	401,
	820,
	117,
	138,
	769,
	768,
	95,
	126,
	84,
	153,
	1171,
	1109,
	385,
	1234,
	81,
	1225,
	1233,
	321,
	143,
	135,
	1231,
	1230,
	1228,
	1452,
	1229,
	1227,
];
module.exports = { dutchTeams, urlsIdDutch };
