const dutchTeams = [
	{ infogol: "Ajax", today: "Ajax", oddsportal: "Ajax" },
	{ infogol: "PSV", today: "PSV", oddsportal: "PSV" },
	{ infogol: "Feyenoord", today: "Feyenoord", oddsportal: "Feyenoord" },
	{ infogol: "Vitesse", today: "Vitesse", oddsportal: "Vitesse" },
	{ infogol: "FC Groningen", today: "Groningen", oddsportal: "Groningen" },
	{ infogol: "FC Twente", today: "Twente", oddsportal: "Twente" },
	{ infogol: "AZ", today: "AZ Alkmaar", oddsportal: "AZ Alkmaar" },
	{ infogol: "SC Heerenveen", today: "Heerenveen", oddsportal: "Heerenveen" },
	{
		infogol: "Sparta Rotterdam",
		today: "Sparta Rotterdam",
		oddsportal: "Sparta Rotterdam",
	},
	{ infogol: "FC Utrecht", today: "Utrecht", oddsportal: "Utrecht" },
	{ infogol: "PEC Zwolle", today: "PEC Zwolle", oddsportal: "Zwolle" },
	{ infogol: "RKC Waalwijk", today: "RKC Waalwijk", oddsportal: "Waalwijk" },
	{ infogol: "Heracles Almelo", today: "Heracles", oddsportal: "Heracles" },
	{
		infogol: "Fortuna Sittard",
		today: "Fortuna Sittard",
		oddsportal: "Sittard",
	},
	{ infogol: "VVV-Venlo", today: "VVV-Venlo", oddsportal: "Venlo" },
	{ infogol: "Willem II", today: "Willem II", oddsportal: "Willem II" },
	{ infogol: "ADO Den Haag", today: "ADO Den Haag", oddsportal: "Den Haag" },
	{ infogol: "FC Emmen", today: "Emmen", oddsportal: "FC Emmen" },
];
const urlsIdDutch = [
	62,
	98,
	116,
	479,
	145,
	331,
	141,
	404,
	1656,
	450,
	1644,
	1650,
	288,
	1639,
	1661,
	1663,
	1617,
	1626,
];
module.exports = { dutchTeams, urlsIdDutch };
