[
	"Norwich City",
	"Bournemouth",
	"Swansea City",
	"Brentford",
	"Watford",
	"Middlesbrough",
	"Stoke City",
	"Reading",
	"Bristol City",
	"Cardiff City",
	"Blackburn Rovers",
	"Huddersfield Town",
	"Barnsley",
	"Luton Town",
	"Preston North End",
	"Millwall",
	"Birmingham City",
	"Coventry City",
	"Queens Park Rangers",
	"Nottingham Forest",
	"Rotherham United",
	"Derby County",
	"Sheffield Wednesday",
	"Wycombe Wanderers"
]